apiVersion: v2
name: canopy-evals-pipeline
description: A Helm chart for Canopy Evals Pipeline using Tekton and Kubeflow
type: application
version: 0.0.8
appVersion: "1.0"
keywords:
  - tekton
  - kubeflow
  - testing
  - llm
  - canopy
home: https://github.com/rhoai-genaiops/genaiops-helmcharts
icon: https://cdn-icons-png.freepik.com/256/11501/11501870.png?semt=ais_white_label
maintainers:
  - name: GenAI Team
    email: genai@redhat.com