---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-science-collector-metrics
  namespace: redhat-ods-monitoring
  labels:
    monitoring.opendatahub.io/scrape: 'true'
spec:
  endpoints:
  - port: prometheus
    path: /metrics
    scheme: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - redhat-ods-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: data-science-collector-collector
