---
apiVersion: v2
description: A little Helm chart for Data Science Pipeline Application ğŸˆ
name: dspa
version: 1.0.0
home: https://rhoai-genaiops.github.io/genaiops/
icon: https://cdn-icons-png.flaticon.com/512/16990/16990376.png 
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili