apiVersion: v2
name: canopy-doc-ingestion-pipeline
description: A Helm chart for Canopy Doc Ingestion Pipeline using Tekton and Kubeflow
type: application
version: 0.0.5
appVersion: "1.0"
keywords:
  - tekton
  - kubeflow
  - testing
  - llm
  - canopy
home: https://github.com/rhoai-genaiops/genaiops-helmcharts
icon: https://cdn-icons-png.flaticon.com/512/10988/10988074.png
maintainers:
  - name: GenAI Team
    email: genai@redhat.com