---
apiVersion: v2
description: A Helm chart for enable and deploy Canopy Grafana Dashboard ðŸ“Š
name: canopy-grafana
version: 0.0.6
home: https://rhoai-genaiops.github.io/genaiops-helmcharts/
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili