---
apiVersion: v2
description: A Helm chart for Guardrails Orchestrator ðŸ”¦
name: guardrails-orchestrator
type: application
version: 1.0.6
appVersion: "latest"
home: https://rhoai-genaiops.github.io/genaiops/
icon: https://cdn-icons-png.freepik.com/512/5896/5896766.png
