---
apiVersion: v2
description: A Helm chart for Llama Stack Operator instances ðŸ¦™
name: llama-stack-operator-instance
type: application
version: 1.1.12
appVersion: "latest"
home: https://rhoai-genaiops.github.io/genaiops/
icon: https://aiagentframeworks.ai/content/images/2024/11/llama-stack.png
keywords:
  - llama-stack
  - ai
  - operator
  - instance
  - mcp
  - agents
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili
